# Generated by Django 3.1.13 on 2021-09-09 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0026_auto_20210521_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='has_completed_onboarding',
            field=models.BooleanField(blank=True, default=False, help_text='Boolean indicating if a project has completed the on-boarding process.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_mme_enabled',
            field=models.BooleanField(default=False),
        ),
    ]

    def apply(self, project_state, schema_editor, collect_sql=False):
        result = super().apply(
            project_state=project_state,
            schema_editor=schema_editor,
            collect_sql=collect_sql
        )

        from ..models import Project

        for project in Project.objects.all():
            project.has_completed_onboarding = True
            project.save()

        return result