# Generated by Django 4.2.15 on 2024-09-08 04:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("seqr", "0063_merge_20240422_0441"),
        ("seqr", "0073_alter_variantfunctionaldata_functional_data_tag"),
    ]

    operations = []
