name: Dockerfile Linting

# Run the test suite on pushes (incl. merges) to master and dev
# Run the test suite when a PR is opened, pushed to, or reopened
on:
  push:
    branches:
      - staging
      - main
    paths:
      - deploy/docker/seqr/Dockerfile
      - hail_search/deploy/Dockerfile
      - .hadolint.yaml
      - .docker-compose.yaml
      - .github/workflows/docker-lint.yaml
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - staging
      - main
    paths:
      - deploy/docker/seqr/Dockerfile
      - hail_search/deploy/Dockerfile
      - .hadolint.yaml
      - .docker-compose.yaml
      - .github/workflows/docker-lint.yaml

jobs:
  hadolint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate docker compose
        run: docker-compose -f docker-compose.yml config
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: deploy/docker/seqr/Dockerfile
          ignore: DL4006 DL3022
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: hail_search/deploy/Dockerfile
